#cloud-config
users:
  - name: yc-user
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    hashed_passwd: ${yc-user-passwd}
    lock_passwd: false
    shell: /bin/bash
    ssh-authorized-keys:
      - ${yc-user-ssh-key}

write_files:
  - path: /etc/ssh/sshd_config.d/extra.conf
    content: |
      AllowUsers yc-user
      PermitRootLogin no
      PasswordAuthentication no
      Port 51222
    owner: root:root
    permissions: '0644'

  - path: /etc/profile.d/extra.sh
    content: |
      export ENV="dev"
    owner: root:root
    permissions: '0644'

runcmd:
  - sudo apt update && sudo apt upgrade -y
